spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/farmaciadb
    username: postgres
    password: 1234
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    sql:
      init:
        mode: always
